services:
  otel-lgtm:
    container_name: otel-lgtm
    image: grafana/otel-lgtm
    ports:
      - '3000:3000' # Grafana
      - '4317:4317' # OTEL GRPC
      - '4318:4318' # OTEL HTTP
      - '3100:3100' # Loki
    environment:
      - GF_PATHS_DATA=/data/grafana
      #- GF_SERVER_HTTP_PORT=2345
    volumes:
      - ./container/grafana:/data/grafana
      - ./container/prometheus:/data/prometheus
      - ./container/loki:/loki
      - ./prometheus.yaml:/otel-lgtm/prometheus.yaml
    stop_grace_period: 500ms

  otel-node-server:
    container_name: otel-node-server
    build:
      context: .
      args:
        APP: otel-node-server
    ports:
      - '4333:4333'
      - '22600:22600'
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
    stop_grace_period: 500ms