# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
    paths:
      - '.github/workflows/deploy-static-site.yml'
      - 'src/react-list/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  react-list:
    needs: checkout
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/react-list
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./src/react-list/package-lock.json

      - name: Install dependencies
        working-directory: ./src/react-list
        run: npm install

      - name: Build
        working-directory: ./src/react-list
        run: npm run build

      - name: Build
        working-directory: ./src/react-list
        run: mkdir -p static-site/react-list && mv dist/* static-site/react-list

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './src/react-list/static-site'

  planets-and-films:
    needs: checkout
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/planets-and-films
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./src/planets-and-films/package-lock.json

      - name: Install dependencies
        working-directory: ./src/planets-and-films
        run: npm install

      - name: Build
        working-directory: ./src/planets-and-films
        run: npm run build

      - name: Build
        working-directory: ./src/planets-and-films
        run: mkdir -p static-site/planets-and-films && mv dist/* static-site/planets-and-films

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './src/planets-and-films/static-site'

  deploy:
    needs: [react-list, planets-and-films]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
